# These are supported funding model platforms

<<<<<<< HEAD
github: meowpoof89
=======
github: # meowpoof89
>>>>>>> b92e11206c2253fb09ab56a67e7b287ad0659549
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
<<<<<<< HEAD
custom: paypal.me/kaylaahensley
=======
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
>>>>>>> b92e11206c2253fb09ab56a67e7b287ad0659549
